services:
  nifi:
    image: apache/nifi:latest
    container_name: etl-nifi
    ports:
      - 8443:8443
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: ${SINGLE_USER_CREDENTIALS_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${SINGLE_USER_CREDENTIALS_PASSWORD}
    # volumes:
    #   - ${NIFI_ROOT_DIR}/nifi_state:/opt/nifi/nifi-current/state
    #   - ${NIFI_ROOT_DIR}/nifi_db:/opt/nifi/nifi-current/database_repository
    #   - ${NIFI_ROOT_DIR}/nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
    #   - ${NIFI_ROOT_DIR}/nifi_content:/opt/nifi/nifi-current/content_repository
    #   - ${NIFI_ROOT_DIR}/nifi_provenance:/opt/nifi/nifi-current/provenance_repository  

  mariadb:
    image: mariadb:latest
    container_name: oltp-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ${MARIADB_ROOT_DIR}/init_sql/:/docker-entrypoint-initdb.d/:ro
      - ${MARIADB_ROOT_DIR}/dataset/:/home/dataset/:ro
      # - ${MARIADB_ROOT_DIR}/db_data:/var/lib/mysql


  adminer:
    image: adminer:latest
    container_name: oltp-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=dracula
    ports:
      - 8080:8080